- name: installing metricbeat

  hosts: all

  become: yes

  tasks:

    - name: downloading metricbeat

      ansible.builtin.apt_key:

        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

        state: present

    - name: installing apttransport

      ansible.builtin.apt:

        name: apt-transport-https

        update_cache: yes

        state: present

    - name: save the repository definition

      ansible.builtin.apt_repository:

        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"

        filename: /etc/apt/sources.list.d/elastic-8.x.list  

        update_cache: true

        state: present

    - name: installing metricbeat

      ansible.builtin.apt:

        name: metricbeat

        update_cache: yes

        state: present

    - name: enabling metricbeat

      ansible.builtin.systemd:

        name: metricbeat

        enabled: true

        state: started