---
  - name: install dotnet-7 in ubuntu 22.04
    hosts: all
    become: yes 
    tasks:
      - name: update packages and install dotnet-7
        ansible.builtin.apt:
          - name: dotnet-7
            state: present
            update_cache: yes

