---
  - name: Installing Broadleaf Commerce
    hosts: Ubuntu
    become: yes
    tasks:
      - name: Clonning repo from git
        ansible.builtin.git:
          repo: https://github.com/BroadleafCommerce/DemoSite.git
          dest: /DemoSite
          clone: yes
          update: no
      - name: Installing maven
        ansible.builtin.apt:
          name: maven
          update_cache: yes
          state: present
      - name: Create directory if doesn't exist
        ansible.builtin.file:
          path: /DemoSite
          state: directory
      - name: Running command 
        ansible.builtin.shell:
          cmd: cd /DemoSite && mvn clean install
      - name: Create a directory if doesn't exist
        ansible.builtin.file:
          path: /DemoSite/site
          state: directory
      - name: Copying the service file to run the service
        ansible.builtin.copy:
          src: broadleaf.service
          dest: /DemoSite/site/broadleaf.service
      - name: coping service using jinja2
        ansible.builtin.template:
          src: templates/broadleaf.service.j2
          dest: /DemoSite/site/broadleaf.service
        notify:
          - restart broadleaf
    handlers:
    - name: restart broadleaf
      ansible.builtin.systemd:
        name: broadleaf
          