---
- name: install openjdk-11-jdk
  hosts: all
  become: true
  tasks:
    - name: install java-11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present